spring:
  application:
    name: libraryapi
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DATASOURCE_USERNAME:toor}
    password: ${DATASOURCE_PASSWORD:pass@123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  sql:
    init:
      mode: always

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        lucasfrancobn:
          libraryapi: trace
    org:
      springframework:
        web: debug
        security: trace

management:
  server:
    # permite mudarmos a porta utilizada pelo actuator
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'


springdoc:
  override-with-generic-response: false

# producao
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false